### ISSUE TITLE
litri

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/while#1]
![es3_17](https://cloud.githubusercontent.com/assets/3002194/20759796/4d1948e8-b71e-11e6-8e16-b9ba05bffe24.png)

**Comment by FabioZTessitore** [comment]
cerca di usare lo schema del ciclo while a sentinella

**Comment by FabioZTessitore** [comment]
perché non vuoi usare lo schema che ti ho dato? cosa c'è che non ti convince?

**Comment by FabioZTessitore** [comment]
spiacente, devi fare come in while3.c

**Comment by CarloRuzzon** [comment]
Prof, volete che la prima volta chieda fuori dal while sia km che litri, vero?

**Comment by FabioZTessitore** [comment]
Solo ciò che viene controllato

Il giovedì 1 dicembre 2016, CarloRuzzon <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
la media finale non è corretta. Chi ti ha insegnato a fare così?

**Comment by CarloRuzzon** [comment]
Ma come prof, la media é data dalla somma di tutti i numeri (a) diviso il
conteggio dell'inserimento dei numeri (cont)

Il 2 dic 2016 3:12 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
ma `a` che cos'è?

**Comment by CarloRuzzon** [comment]
Ai litri/km

**Comment by FabioZTessitore** [comment]
appunto, è già una media. Quindi tu calcoli la media della media

**Comment by CarloRuzzon** [comment]
Non ho capito bene cosa devo fare 😂

Il 2 dic 2016 3:27 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
alla fine deve stampare la media km_totali / litri_totali
