### ISSUE TITLE
quadrato

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/while#10]
![es3_33](https://cloud.githubusercontent.com/assets/3002194/21102011/5bf7164e-c07c-11e6-8bee-376fb8f3bd13.png)

**Comment by CarloRuzzon** [comment]
Prof ma ci vuole l'if per gestire ogni caso...?

**Comment by FabioZTessitore** [comment]
a che ti riferisci?

**Comment by CarloRuzzon** [comment]
Ai quadrati da disegnare

Il 13 dic 2016 6:05 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Non capisco. Devi farti dare in input un numero e stampare il quadrato

**Comment by CarloRuzzon** [comment]
Si, ma devo disegnarli i quadrati, come faccio?

Il 13 dic 2016 7:38 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
non sai disegnare degli asterischi?

**Comment by CarloRuzzon** [comment]
Tutti i quadrati tra 1 e 20, devo fare 20 casi?

**Comment by FabioZTessitore** [comment]
Ma non devi stampare 20 quadrati. Solo uno. Però il lato deve essere
inserito e deve essere compreso tra 1 e 20

Il martedì 13 dicembre 2016, CarloRuzzon <notifications@github.com> ha
scritto:

**Comment by CarloRuzzon** [comment]
Vi ho capito, ma se metto 1 dovrà uscire *
Se metto due, un quadratino di quattro asterischi, e cosí via, ma gli
asterischi non si possono incrementare, devo fare 20 casi diversi?

Il 13 dic 2016 8:08 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
no, devi trovare un algoritmo che vale per tutti

**Comment by FabioZTessitore** [comment]
la parte della stampa del quadrato va bene.
non va bene il do-while. Dovrebbe servire a farti ridare il valore se non è compreso nell'intervallo previsto

**Comment by FabioZTessitore** [comment]
non ci siamo capiti, che succede se metto 30?

**Comment by CarloRuzzon** [comment]
Che prima lo esegue e dopo ricomincia, ma questa é la struttura, volete un
while?


Il 16 dic 2016 9:28 PM, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Non è la struttura. È come la usi

Prima bisogna avere un input corretto, poi si disegna

Il venerdì 16 dicembre 2016, CarloRuzzon <notifications@github.com> ha
scritto:

**Comment by CarloRuzzon** [comment]
Glielo faccio richiedere quando il numero inserito non è corretto, se inserisco trenta, lo fa e lo richiede

**Comment by FabioZTessitore** [comment]
appunto, se metti 30 non deve disegnare, deve richiedere
