### ISSUE TITLE
due maggiori

### ISSUE THREAD

**Issue by FabioZTessitore** [CarloRuzzon/while#8]
![es3_27](https://cloud.githubusercontent.com/assets/3002194/20890962/29467938-bb09-11e6-8cfc-1c71f24dc400.png)

**Comment by FabioZTessitore** [comment]
non funziona

**Comment by CarloRuzzon** [comment]
Ma come, io l'ho testato e funziona...

**Comment by FabioZTessitore** [comment]
devi fare attenzione quando fai i test,
prova ad inserire i valori da 10 a 0
